cluster.name: "camel-mq-processor"
node.name: "elasticsearch-config"

# Network settings
network.host: 0.0.0.0
http.port: 9200

# Discovery settings for single node
discovery.type: single-node

# Security settings
xpack.security.enabled: true
xpack.security.authc.anonymous.roles: superuser
xpack.security.transport.ssl.enabled: false
xpack.security.http.ssl.enabled: false

# Performance settings
bootstrap.memory_lock: false
indices.query.bool.max_clause_count: 10000

# Logging
logger.org.elasticsearch.deprecation: WARN