# Enhanced Camel MQ Processor Configuration
# Thread Isolation + Circuit Breakers + Monitoring = 🔥

server:
  port: 8080

spring:
  application:
    name: camel-mq-processor-enhanced
  
  # Redis Configuration for Caching
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 5
  
  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: 30000
    publisher-confirm-type: simple
    cache:
      connection:
        mode: channel
      channel:
        size: 100

  # Elasticsearch Configuration
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD:elastic123}
    connection-timeout: 30s
    socket-timeout: 30s

# Camel Configuration
camel:
  springboot:
    name: enhanced-camel-context
    shutdown-timeout: 30
    use-mdc-logging: true
    message-history: true
  
# Circuit Breaker Configuration (Resilience4j)
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 30s
        sliding-window-size: 20
        sliding-window-type: count_based
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      # Default config for all partners
      partner-default:
        base-config: default

  # Bulkhead Configuration
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 25
        max-wait-duration: 1000ms
    instances:
      partner-default:
        base-config: default

# Monitoring and Metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,threaddump
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        resilience4j.circuitbreaker.calls: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
        resilience4j.circuitbreaker.calls: 0.5,0.95,0.99

# Logging Configuration
logging:
  level:
    com.company.camel: INFO
    org.apache.camel: WARN
    io.github.resilience4j: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{partner}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{partner}] %logger{36} - %msg%n"

# Custom Application Properties
app:
  # Thread Pool Settings
  thread-pool:
    default:
      core-size: 5
      max-size: 20
      queue-capacity: 1000
      keep-alive-seconds: 60
  
  # Circuit Breaker Settings
  circuit-breaker:
    failure-threshold: 50
    timeout-seconds: 30
    recovery-timeout-seconds: 60
  
  # Partner Configuration
  partners:
    # Will be loaded from Elasticsearch
    load-from-elastic: true
    default-consumer-count: 10
    config-refresh-interval: 300s
    
  # Partner-specific Configuration
  partner-config:
    index: partner-configurations
    refresh-interval-seconds: 30
    enable-dynamic-routes: true
    
  # Route Template Configuration  
  routes:
    templates:
      enabled: true
      partner-processing-template: partnerProcessingTemplate
    legacy:
      enabled: false  # Disable old shared route
  
  # Monitoring
  monitoring:
    metrics-enabled: true
    health-check-interval: 30s
    
# Jasypt Encryption (for sensitive properties)
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator