# Enhanced Camel MQ Processor - Production Configuration
# Thread Isolation + Circuit Breakers + Live Message Processing = 🔥

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,threaddump,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
        step: 10s
    distribution:
      percentiles-histogram:
        http.server.requests: true
        resilience4j.circuitbreaker.calls: true
        partner.threadpool.active: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
        resilience4j.circuitbreaker.calls: 0.5,0.95,0.99

spring:
  application:
    name: camel-mq-processor-enhanced
  
  # RabbitMQ Configuration for Live Message Consumption
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin123}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: 30000
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 2.0
    listener:
      simple:
        concurrency: 10
        max-concurrency: 50
        prefetch: 10
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          max-interval: 10000ms
          multiplier: 2.0
    cache:
      connection:
        mode: channel
      channel:
        size: 200

  # Redis Configuration for Caching
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 5000ms
    database: 0
    jedis:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 10
        max-wait: 2000ms

  # Elasticsearch Configuration for Partner Config
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9200}
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD:elastic123}
    connection-timeout: 10s
    socket-timeout: 30s

# Camel Configuration for Live Processing
camel:
  springboot:
    name: enhanced-camel-context-production
    shutdown-timeout: 60
    use-mdc-logging: true
    message-history: true
    stream-caching-enabled: true
    stream-caching-spool-threshold: 131072
  
  # Component configurations
  component:
    rabbitmq:
      connection-factory: "#rabbitConnectionFactory"
      auto-startup: true
    
    http:
      connection-timeout: 30000
      socket-timeout: 60000
      connection-request-timeout: 10000

# Circuit Breaker Configuration (Resilience4j) - Production Tuned
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 60
        minimum-number-of-calls: 20
        wait-duration-in-open-state: 60s
        sliding-window-size: 50
        sliding-window-type: count_based
        permitted-number-of-calls-in-half-open-state: 10
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.io.IOException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
    instances:
      # High-priority partners
      amazon:
        base-config: default
        failure-rate-threshold: 70
        minimum-number-of-calls: 30
        wait-duration-in-open-state: 45s
      flipkart:
        base-config: default
        failure-rate-threshold: 70
        minimum-number-of-calls: 30
        wait-duration-in-open-state: 45s
      # Medium-priority partners
      myntra:
        base-config: default
        failure-rate-threshold: 60
        minimum-number-of-calls: 20
        wait-duration-in-open-state: 60s
      # Default for all other partners
      partner-default:
        base-config: default

  # Bulkhead Configuration
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 50
        max-wait-duration: 2000ms
    instances:
      amazon:
        max-concurrent-calls: 100
        max-wait-duration: 1000ms
      flipkart:
        max-concurrent-calls: 80
        max-wait-duration: 1500ms
      partner-default:
        base-config: default

  # Retry Configuration
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 1000ms
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
    instances:
      partner-default:
        base-config: default

# Logging Configuration for Production
logging:
  level:
    root: INFO
    com.company.camel: INFO
    org.apache.camel: WARN
    io.github.resilience4j: INFO
    org.springframework.amqp: WARN
    org.elasticsearch: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{partner}] [%X{correlationId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{partner}] [%X{correlationId}] %logger{36} - %msg%n"
  file:
    name: /app/logs/camel-mq-processor.log
    max-size: 100MB
    max-history: 30

# Custom Application Properties for Production
app:
  # Thread Pool Settings - Production Optimized
  thread-pool:
    default:
      core-size: 10
      max-size: 50
      queue-capacity: 2000
      keep-alive-seconds: 300
    high-priority:
      core-size: 20
      max-size: 100
      queue-capacity: 5000
      keep-alive-seconds: 600
  
  # Circuit Breaker Settings
  circuit-breaker:
    failure-threshold: 60
    timeout-seconds: 60
    recovery-timeout-seconds: 120
  
  # Partner Configuration
  partners:
    load-from-elastic: true
    default-consumer-count: 20
    config-refresh-interval: 300s
    health-check-interval: 60s
  
  # Message Processing
  message:
    max-retry-attempts: 5
    retry-delay-ms: 2000
    dead-letter-enabled: true
    correlation-tracking: true
  
  # Monitoring
  monitoring:
    metrics-enabled: true
    health-check-interval: 30s
    partner-stats-interval: 15s
    
  # Performance Tuning
  performance:
    async-processing: true
    batch-size: 100
    flush-interval: 5s
    connection-pool-size: 50

# Jasypt Encryption for Production Secrets
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    password: ${JASYPT_ENCRYPTOR_PASSWORD:changeme}